# Generated by Django 6.0.7 on 2026-07-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools'), ('Cloud', 'Cloud'), ('Other', 'Other')], default='Other', max_length=50)),
                ('proficiency', models.PositiveIntegerField(help_text='Enter value between 0 and 100')),
                ('icon', models.CharField(blank=True, help_text='Example: fa-python', max_length=100)),
            ],
        ),
    ]
